---
# This is an example config layout

# Defines project name which becomes parent root directory
project_name: example

# Define backends
backends:
  local: {}
  remote: {}

# Defines environments
environments:
  development: {}
  production: {}
  staging: {}

# Define global variables
global_variables: {}

# Define modules - Structure will be project_name/modules/{module}
# root needs to always exist
modules:
  root: {}
  network: {}
  services: {}

# Define providers
providers:
  AzureRM:
    environment: var.azrm_environment
    features: {}
    subscription_id: var.azrm_subscription_id
    tenant_id: var.azrm_tenant_id
    variables:
      azrm_environment:
        type: string
        description: AzureRM Environment
        default: public
      azrm_subscription_id:
        type: string
        description: AzureRM Subscription ID
        default: ""
      azrm_tenant_id:
        type: string
        description: AzureRM Tenant ID
        default: ""
  DigitalOcean:
    api_endpoint: https://api.digitalocean.com
    token: var.do_token
    variables:
      do_region:
        type: string
        description: DigitalOcean region
        default: nyc1
      do_ssh_keys:
        type: string
        description: DigitalOcean SSH keys to deploy to new droplets
        default: []
      do_token:
        type: string
        description: DigitialOcean token
        default: ""
  vSphere:
    allow_unverified_ssl: var.vsphere_allow_unverified_ssl
    password: var.vsphere_password
    user: var.vsphere_username
    vsphere_server: var.vsphere_server
    variables:
      vsphere_allow_unverified_ssl:
        type: bool
        description: Boolean that can be set to true to disable SSL certificate verification
        default: "false"
      vsphere_password:
        type: string
        description: Password for vSphere API operations
        default: ""
      vsphere_server:
        type: string
        description: vCenter server name for vSphere API operations
        default: ""
      vsphere_username:
        type: string
        description: Username for vSphere API operations
        default: ""

# Define required resources including provider and module
resources:
  projects:
    TerraformCloud:
      description: Terraform Cloud Project
      environment: development
      module: root
      provider: DigitalOcean
      purpose: Terraform Cloud Project
      resources: []
      tags:
        - test
  vms:
    test:
      count: 1
      image: ubuntu-18-04-x64
      module: root
      private_networking: true
      provider: DigitalOcean
      region: var.do_region
      ssh_keys: var.do_ssh_keys
      size: s-1vcpu-2gb
      tags:
        - test
