---
# This is an example config layout

# Defines project name which becomes parent root directory
project_name: example

# Define backends
backends:
  local: {}
  remote: {}

# Defines environments
environments:
  development: {}
  production: {}
  staging: {}

# Define global variables
global_variables: {}

# Define modules - Structure will be project_name/modules/{module}
# root needs to always exist
modules:
  root: {}
  network: {}
  services: {}

# Define providers and variables
providers:
  AzureRM:
    resources:
      networks:
        example:
          create: true
          module: services
          network: 10.0.0.0/16
          resource_group: example
          subnets:
            - 10.0.1.0/24
            - 10.0.2.0/24
      resource_groups:
        default:
          create: false
          module: root
        example:
          create: true
          module: services
      vms:
        test-az-root:
          count: 2
          image: ubuntu-18-04-x64
          memory: 1024
          module: services
          network: example
          subnet: 10.0.2.0/24
          num_cpus: 1
          tags:
            - test-azurerm
            - test-azurerm-root
    variables:
      azurerm_domain:
        type: string
        description: Default AzureRM domain for resources
        default: ""
      azurerm_environment:
        type: string
        description: AzureRM Environment
        default: public
      azurerm_features:
        description: Customize the behaviour of certain Azure Provider resources.
        default: {}
      azurerm_image_reference:
        description: Default OS image reference lookups
        default:
          {
            "ubuntu-16-04-x64":
              {
                "publisher": "Canonical",
                "offer": "UbuntuServer",
                "sku": "16.04-LTS",
                "version": "latest",
              },
            "ubuntu-18-04-x64":
              {
                "publisher": "Canonical",
                "offer": "UbuntuServer",
                "sku": "18.04-LTS",
                "version": "latest",
              },
          }
      azurerm_location:
        type: string
        description: Default AzureRM location/region
        default: East US
      azurerm_subscription_id:
        type: string
        description: AzureRM Subscription ID
        default: ""
      azurerm_tenant_id:
        type: string
        description: AzureRM Tenant ID
        default: ""
  DigitalOcean:
    resources:
      vms:
        test-do-root:
          count: 1
          image: ubuntu-18-04-x64
          memory: 1024
          module: root
          num_cpus: 1
          tags:
            - test-digitalocean
            - test-digitalocean-root
        test-do-network:
          count: 1
          image: ubuntu-18-04-x64
          memory: 1024
          module: network
          num_cpus: 1
          tags:
            - test-digitalocean
            - test-digitalocean-network
    variables:
      do_api_endpoint:
        type: string
        description: This can be used to override the base URL for DigitalOcean API requests
        default: https://api.digitalocean.com
      do_domain:
        type: string
        description: Default DigitalOcean domain for resources
        default: ""
      do_region:
        type: string
        description: DigitalOcean region
        default: nyc1
      do_ssh_keys:
        type: string
        description: DigitalOcean SSH keys to deploy to new droplets
        default: []
      do_token:
        type: string
        description: This is the DO API token
        default: ""
  vSphere:
    resources:
      vms:
        test-vs-root:
          count: 1
          memory: 2048
          module: root
          num_cpus: 1
          tags:
            - test-vsphere
            - test-vsphere-root
        test-vs-services:
          count: 1
          memory: 1024
          module: services
          num_cpus: 2
          tags:
            - test-vsphere
            - test-vsphere-services
    variables:
      vsphere_allow_unverified_ssl:
        type: bool
        description: Boolean that can be set to true to disable SSL certificate verification
        default: "false"
      vsphere_compute_cluster:
        type: string
        description: Compute cluster to use by default
        default: ""
      vsphere_datacenter:
        type: string
        description: Datacenter to use by default
        default: ""
      vsphere_network:
        type: string
        description: Network to use by default
        default: ""
      vsphere_password:
        type: string
        description: Password for vSphere API operations
        default: ""
      vsphere_resource_pool:
        type: string
        description: The resource pool to put virtual machine's in
        default: ""
      vsphere_server:
        type: string
        description: vCenter server name for vSphere API operations
        default: ""
      vsphere_username:
        type: string
        description: Username for vSphere API operations
        default: ""
