---
# This is an example config layout

# Defines project name which becomes parent root directory
project_name: example

# Define backends
backends:
  local: {}
  remote: {}

# Defines environments
environments:
  development: {}
  production: {}
  staging: {}

# Define global variables
global_variables: {}

# Define modules - Structure will be project_name/modules/{module}
# root needs to always exist
modules:
  root: {}
  network: {}
  services: {}

# Define providers and variables
providers:
  AzureRM:
    resources:
      resource_groups:
        example-rg-root:
          create: true
          module: root
          virtual_networks:
            example-net:
              address_space:
                - 10.0.0.0/16
              create: true
              subnets:
                - 10.0.1.0/24
                - 10.0.2.0/24
          vms:
            example-vm-root:
              count: 1
              image: ubuntu-18-04-x64
              memory: 1024
              network: example-net
              subnet: 10.0.2.0/24
              num_cpus: 1
              tags: { "environment": "${var.environment}" }
    variables:
      azurerm_client_id:
        type: string
        description: Default AzureRM client id
        default: ""
      azurerm_client_secret:
        type: string
        description: Default AzureRM client secret
        default: ""
      azurerm_domain:
        type: string
        description: Default AzureRM domain for resources
        default: ""
      azurerm_environment:
        type: string
        description: AzureRM Environment
        default: public
      azurerm_features:
        description: Customize the behaviour of certain Azure Provider resources.
        default: {}
      azurerm_image_reference:
        description: Default OS image reference lookups
        default:
          {
            "ubuntu-16-04-x64":
              {
                "publisher": "Canonical",
                "offer": "UbuntuServer",
                "sku": "16.04-LTS",
                "version": "latest",
              },
            "ubuntu-18-04-x64":
              {
                "publisher": "Canonical",
                "offer": "UbuntuServer",
                "sku": "18.04-LTS",
                "version": "latest",
              },
          }
      azurerm_location:
        type: string
        description: Default AzureRM location/region
        default: East US
      azurerm_subscription_id:
        type: string
        description: AzureRM Subscription ID
        default: ""
      azurerm_tenant_id:
        type: string
        description: AzureRM Tenant ID
        default: ""
  DigitalOcean:
    resources:
      vms:
        test-do-root:
          count: 1
          image: ubuntu-18-04-x64
          memory: 1024
          module: root
          num_cpus: 1
          tags:
            - test-digitalocean
            - test-digitalocean-root
        test-do-network:
          count: 1
          image: ubuntu-18-04-x64
          memory: 1024
          module: network
          num_cpus: 1
          tags:
            - test-digitalocean
            - test-digitalocean-network
    variables:
      do_api_endpoint:
        type: string
        description: This can be used to override the base URL for DigitalOcean API requests
        default: https://api.digitalocean.com
      do_domain:
        type: string
        description: Default DigitalOcean domain for resources
        default: ""
      do_region:
        type: string
        description: DigitalOcean region
        default: nyc1
      do_ssh_keys:
        type: string
        description: DigitalOcean SSH keys to deploy to new droplets
        default: []
      do_token:
        type: string
        description: This is the DO API token
        default: ""
  vSphere:
    resources:
      datacenters:
        example-dc:
          clusters:
            example-cluster:
              create: true
              drs_enabled: true
              drs_automation_level: fullyAutomated
              ha_enabled: true
              hosts:
                example-esxi-01:
                  create: true
                  hostname: 10.10.10.1
              vms:
                example-vm:
                  count: 1
                  memory: 2048
                  network: example-pg
                  num_cpus: 1
                  tags:
                    - example-vsphere
                  template: ""
                example-vm-from-template:
                  count: 1
                  memory: 2048
                  network: example-pg
                  num_cpus: 1
                  tags:
                    - example-vsphere
                  template: ubuntu-18-04-x64
          create: true
          module: root
          templates:
            - ubuntu-16-04-x64
            - ubuntu-18-04-x64
          virtual_switches:
            example-switch:
              create: true
              type: host
              network_adapters:
                - vmnic0
                - vmnic1
              active_nics:
                - vmnic0
              standby_nics:
                - vmnic1
              teaming_policy: loadbalance_srcid
              port_groups:
                example-pg:
                  create: true
      tag_categories:
        example-category:
          associable_types:
            - ClusterComputeResource
            - Datacenter
            - Datastore
            - HostSystem
            - VirtualMachine
          cardinality: SINGLE
          create: true
          module: root
          tags:
            - example-vsphere
    variables:
      vsphere_allow_unverified_ssl:
        type: bool
        description: Boolean that can be set to true to disable SSL certificate verification
        default: "false"
      vsphere_host_password:
        type: string
        description: Password for vSphere hosts
        default: ""
      vsphere_host_username:
        type: string
        description: Username for vSphere hosts
        default: ""
      vsphere_password:
        type: string
        description: Password for vSphere API operations
        default: ""
      vsphere_server:
        type: string
        description: vCenter server name for vSphere API operations
        default: ""
      vsphere_username:
        type: string
        description: Username for vSphere API operations
        default: ""
